sudo: required
language: php
php:
  - 5.5
  - 5.6
  - 7.0
env:
  - MERCHANT_ID=454 PASS_CODE=t7Dop1ql%!nD PSIGN_ALGORITHM=sha1 REMOTE_URL=https://secure.aldrapay.com
before_install:
  - sudo apt-get -y install git zip php5-cli php5-curl gnutls-bin
before_script:
  - sudo apt-get update
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  # enable php-fpm
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - sudo sed -i -e "s,www-data,travis,g" /etc/apache2/envvars
  - sudo chown -R travis:travis /var/lib/apache2/fastcgi
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  # configure apache virtual hosts
  - sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/000-default.conf
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/000-default.conf
  - sudo service apache2 restart
script:
  - "gnutls-cli --priority \"NORMAL:-VERS-TLS-ALL:+VERS-TLS1.1\" secure.aldrapay.com"
  - "gnutls-cli --priority \"NORMAL:-VERS-TLS-ALL:+VERS-TLS1.0\" secure.aldrapay.com"
  - "cd ./test && ./run-tests.sh"
