sudo: required
language: php
matrix:
  include:
    - php: 5.5
      env: RUNNABLE_PHPVER=5.5
    - php: 5.6
      env: RUNNABLE_PHPVER=5.6
    - php: 7.0
      env: RUNNABLE_PHPVER=7.0
before_script:
  - sudo apt-get update
  - sudo apt-get -y install git zip php5-cli php5-curl
script:
  - "cd ./test && ./run-tests.sh"
