sudo: required
language: php
php:
  - 5.5
  - 5.6
  - 7.0
env:
  - MERCHANT_ID=454 PASS_CODE=t7Dop1ql%!nD PSIGN_ALGORITHM=sha1 REMOTE_URL=https://secure.aldrapay.com
before_install:
  - sudo apt-get -y install git zip php5-cli php5-curl
before_script:
  - php -r "printf('PHP %s', phpversion());"
  - composer self-update
  - composer install --no-interaction
script:
  - "gnutls-cli --priority \"NORMAL:-VERS-TLS-ALL:+VERS-TLS1.1\" secure.aldrapay.com"
  - "gnutls-cli --priority \"NORMAL:-VERS-TLS-ALL:+VERS-TLS1.0\" secure.aldrapay.com"
  - "cd ./test && ./run-tests.sh"
