sudo: required
language: php
php:
  - 5.5
  - 5.6
  - 7.0
env:
  - MERCHANT_ID=457 PASS_CODE=t7Dop1ql%!nD PSIGN_ALGORITHM=sha1 REMOTE_URL=https://stpdirect.aldrapay.com
before_script:
  - sudo apt-get update
  - sudo apt-get -y install git zip php5-cli php5-curl
script:
  - "cd ./test && ./run-tests.sh"
